on:
  push:
    branches:
      - master
name: cd
jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bcoe/release-please-action@v1.2.2
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          package-name: forest-night
      # The logic below handles JetBrains publication:
      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-java@v1
        with:
          java-version: 11
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
        if: ${{ steps.release.outputs.release_created }}
      - run: ./gradlew publishPlugin --stacktrace
        env:
          JETBRAINS_TOKEN: ${{ secrets.JETBRAINS_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}
